// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/chat": {
    params: {};
  };
  "/api/agents": {
    params: {};
  };
  "/api/projects": {
    params: {};
  };
  "/api/versions": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/chat" | "/api/agents" | "/api/projects" | "/api/versions";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/api.chat.ts": {
    id: "routes/api.chat";
    page: "/api/chat";
  };
  "routes/api.agents.ts": {
    id: "routes/api.agents";
    page: "/api/agents";
  };
  "routes/api.projects.ts": {
    id: "routes/api.projects";
    page: "/api/projects";
  };
  "routes/api.versions.ts": {
    id: "routes/api.versions";
    page: "/api/versions";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/api.chat": typeof import("./app/routes/api.chat.ts");
  "routes/api.agents": typeof import("./app/routes/api.agents.ts");
  "routes/api.projects": typeof import("./app/routes/api.projects.ts");
  "routes/api.versions": typeof import("./app/routes/api.versions.ts");
};