import type { editor } from "monaco-editor";

export const NEON_THEME_NAME = "neon-void";

export const neonThemeData: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "e8e8f0", background: "0a0a0f" },
    { token: "comment", foreground: "686880", fontStyle: "italic" },
    { token: "keyword", foreground: "ffd700" },
    { token: "string", foreground: "00f5ff" },
    { token: "number", foreground: "ff00ff" },
    { token: "type", foreground: "8b5cf6" },
    { token: "function", foreground: "f4a836" },
    { token: "variable", foreground: "e8e8f0" },
    { token: "operator", foreground: "ffd700" },
    { token: "delimiter", foreground: "9898b0" },
    { token: "tag", foreground: "ffd700" },
    { token: "attribute.name", foreground: "8b5cf6" },
    { token: "attribute.value", foreground: "00f5ff" },
    { token: "regexp", foreground: "00ff88" },
    { token: "constant", foreground: "ff00ff" },
  ],
  colors: {
    "editor.background": "#0a0a0f",
    "editor.foreground": "#e8e8f0",
    "editor.lineHighlightBackground": "#12121f",
    "editor.selectionBackground": "#ffd70030",
    "editor.inactiveSelectionBackground": "#ffd70015",
    "editorLineNumber.foreground": "#686880",
    "editorLineNumber.activeForeground": "#ffd700",
    "editorCursor.foreground": "#ffd700",
    "editorWhitespace.foreground": "#1a1a2e",
    "editorIndentGuide.background": "#1a1a2e",
    "editorIndentGuide.activeBackground": "#ffd70030",
    "editor.findMatchBackground": "#ffd70040",
    "editor.findMatchHighlightBackground": "#ffd70020",
    "editorBracketMatch.background": "#ffd70020",
    "editorBracketMatch.border": "#ffd70050",
    "editorGutter.background": "#0a0a0f",
    "editorWidget.background": "#12121f",
    "editorWidget.border": "#ffd70020",
    "input.background": "#0d0d1a",
    "input.border": "#ffd70020",
    "scrollbarSlider.background": "#ffd70015",
    "scrollbarSlider.hoverBackground": "#ffd70030",
    "scrollbarSlider.activeBackground": "#ffd70040",
  },
};
